# Generated by Django 5.1.3 on 2025-03-04 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vieweremail',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vieweremail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
